[tool.poetry]
name = "poetrytest2"
version = "0.1.0"
description = ""
authors = ["MT"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
numpy = "^2.0.0"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
